const input =document.querySelector('input')
const button =document.querySelector('button')
const list =document.querySelector('list')
const li =document.createElement('li')
const deleat=document.createElement('button')